#include <iostream.h>
#include <conio.h>
void main()
{
	clrscr();
	cout << (char)201<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<(char)205<<endl;
	cout <<(char)179<<"Nama   : Sri Hartati Wijoyo \n Nomor : 105314012 \n Alamat : Jl. Tasura 1234 Paingan "<<(char)179<<endl;
	cout <<(char)192<<(char)196<<(char)196<<(char)196<<(char)196<<(char)217<<endl;
	getch();
}